name: Secure Docker Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macOS-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Validate Docker installation
      run: docker --version
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Create .npmrc secret file
      run: |
        echo "registry=https://registry.npmjs.org/" > .npmrc
        echo "//registry.npmjs.org/:_authToken=${{ secrets